### PR TITLE
Namsonx/task/stabi branch

### PR DESCRIPTION
**Pull request by namsonx**
Hello Thomas,

I create this pull-request for JsonPreprocessor's code optimization plus some bugs fixing.

Thank you,
Son

### CODE REVIEW

**Review by HolQue — COMMENTED** [review]
Yesterday I resolved a merge conflict caused by interface descriptions adapted by me. I also adapted the interface description of __nestedParamHandler. In this pull request my changes are gone and the previous version is back.

Accidental copy&paste issue?

**Comment by namsonx** [comment]
> Yesterday I resolved a merge conflict caused by interface descriptions adapted by me. I also adapted the interface description of __nestedParamHandler. In this pull request my changes are gone and the previous version is back.
> 
> Accidental copy&paste issue?

Hello Holger,

This is the accident when I merged, I will check and update your descriptions

Thank you,
Son

**Comment by HolQue** [comment]
JsonPreprocessor still freezes. But now at another position within the test sequence.

I will try to find the exact position.

**Comment by namsonx** [comment]
> > Yesterday I resolved a merge conflict caused by interface descriptions adapted by me. I also adapted the interface description of __nestedParamHandler. In this pull request my changes are gone and the previous version is back.
> > Accidental copy&paste issue?
> 
> Hello Holger,
> 
> This is the accident when I merged, I will check and update your descriptions
> 
> Thank you, Son

Hello Holger,

I updated the descriptions back.

Thank you!

**Pull request merged**
