### PR TITLE
Added JPP_1000 to test the implicit creation of data structures

### PR DESCRIPTION
**Pull request by HolQue**
Hi Son,

in opposite to

https://github.com/test-fullautomation/robotframework-testsuitesmanagement/issues/214

this new test case JPP_1000 is successful.

### CODE REVIEW

**Comment by test-fullautomation** [comment]
Hi Holger,
hm... to avoid confutions I would propose to create pull-requests only against @namsonx 's stabi branch?
Thank you,
 Thomas

**Review by test-fullautomation — CHANGES_REQUESTED** [review]
Hi Holger,
please check my finding.
Thank you,
 Thomas

**Comment by HolQue** [comment]
Hi Thomas,

I wanted to do this. Most probably a clicking mistake. I retry.

**Comment by HolQue** [comment]
Hi Thomas,

Successor of this pull request is:

https://github.com/test-fullautomation/python-jsonpreprocessor/pull/141

This pull request can be deleted.

**Comment by test-fullautomation** [comment]
closed due to accidentally wrong destination branch.

**Pull request closed without merging**
