### PR TITLE
Namsonx/task/stabi branch

### PR DESCRIPTION
**Pull request by namsonx**

### CODE REVIEW

**Comment by test-fullautomation** [comment]
Hi @namsonx ,
does this contain already a solution for #390?
Thank you,
 Thomas

**Comment by namsonx** [comment]
> Hi @namsonx , does this contain already a solution for #390? Thank you, Thomas

Hello Thomas,

The solution for #390 included in this pull-request.

Thank you,
Son

**Comment by test-fullautomation** [comment]
Hi  @namsonx , @HolQue ,
very good!
O.K. then I wait for feedback from Holger to merge.
This is then the last pull-request for 0.13.1 from you Son, correct? (If Holger doesn't find a stopper).
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas,

Yes, this is the last pull-request for 0.13.1 from my side.

Thank you,
Son

**Comment by test-fullautomation** [comment]
Hi @HolQue ,
I wait for your "Go".
Thank you,
 Thomas

**Pull request merged**
