### PR TITLE
Namsonx/task/stabi branch

### PR DESCRIPTION
**Pull request by namsonx**

### CODE REVIEW

**Comment by test-fullautomation** [comment]
Hi @namsonx ,
as discussed today I wait for an update of the "_" documentation before merging.
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas,

I already updated the release note information.

Thank you,
Son

**Review by test-fullautomation — APPROVED** [review]
Hi Son,
looks good to me!
Thank you,
 Thomas

**Review by test-fullautomation — APPROVED** [review]
Hi Son,
very good!
Thank you,
 Thomas

**Pull request merged**
