### PR TITLE
Namsonx/task/stabi branch

### PR DESCRIPTION
**Pull request by namsonx**

### CODE REVIEW

**Review by HolQue — CHANGES_REQUESTED** [review]
Hi Son,

History: "_Improved error message logs_"

We do not have _error message logs_. Maybe you mean: _Improved error messages_?

No need to mention "_logs_", because some error messages are also written to console.

Therefore "_Improved error messages_" is enough.

You increased the version number from 0.5.0 to 0.5.1. This indicates a patch. But when you implement a new feature like the blocking of dynamic key names and the changed data type of the return value, this is not a patch any more. Please change the version to 0.6.0.

**Comment by HolQue** [comment]
Hi Son,

release info:

Please keep the example simple. There is no need to use a nested dictionary to explain the blocked dynamic key names.

This code also does - and is much easier to capture:

```
"param1"    : "ABC",
"param2"    : "XYZ",
"${param2}" : ${param1}
```

```
{"param1" : "ABC",
 "param2" : "XYZ",
 "XYZ" : "ABC"}
```

You can tell that "XYZ" now will not be created any more. And you should add a hint telling what happens instead of this: the error message.

**Comment by HolQue** [comment]
Hi Son,

regarding:

```
ERROR - Parameter 'teststring-1' is invalid variable name or conflicts with Robot reserved keywords.
ERROR - Variable names in Robot Framework must start with a letter or underscore, followed by letters, digits, or underscores.
UNKNOWN - Exception occurred.
```

caused by

`if not re.match(varNamePattern, k) or k in lReservedKeyword:`

Please separate this. Here we speak about two different things and it's unfavorable to mixup them. Also the wording needs to be fixed.

Better:

**(1)**
```
ERROR - Found invalid parameter name 'teststring-1'.
ERROR - Variable names in Robot Framework must start with a letter or underscore, followed by letters, digits, or underscores.
```

**(2)**
`ERROR - '...'  is a reserved keyword in Robot Framework and cannot be used as parameter name.`

And exchange:

`UNKNOWN - Exception occurred.`

by:

`UNKNOWN - Violation of naming conventions detected. The test execution will be aborted!`

**Comment by HolQue** [comment]
Hi Son,

In case of a missing quotation, e.g:

```
"param1 : 1,
"param2" : 2
```

I get an empty ERROR line:

```
ERROR -
ERROR - No closing quotation in line: '                           "param1 : 1,'
UNKNOWN - Unable to load the test configuration. The test execution will be aborted!
```

Please remove the empty line or fill with content.

**Comment by HolQue** [comment]
Hi Son,

please also consider

https://github.com/test-fullautomation/python-jsonpreprocessor/issues/297

**Comment by test-fullautomation** [comment]
Hi  @namsonx ,  @HolQue ,
can I merge?
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas,

From my site, this pull-request is ready to merge.
Please help me merge this pull-request https://github.com/test-fullautomation/python-extensions-collection/pull/47 first, otherwise the selftest will fail due to dotdict data type.

Thank you,
Son

**Pull request merged**
