### PR TITLE
Namsonx/task/stabi branch

### PR DESCRIPTION
**Pull request by namsonx**
config/robotframework_aio/release_items_JsonPreprocessor.json already updated before

### CODE REVIEW

**Review by test-fullautomation — APPROVED** [review]
Hi Son,
very good!
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
@namsonx , @HolQue 
Hi Son,
the precheck 
https://github.com/test-fullautomation/RobotFramework_AIO/actions/runs/7555223537
has in Windows SelfTest a failure. Can you please check the error cause and confirm that I can merge.
Thank you,
 Thomas

**Comment by namsonx** [comment]
> @namsonx , @HolQue 
> 
> Hi Son,
> 
> the precheck 
> 
> https://github.com/test-fullautomation/RobotFramework_AIO/actions/runs/7555223537
> 
> has in Windows SelfTest a failure. Can you please check the error cause and confirm that I can merge.
> 
> Thank you,
> 
>  Thomas

Hello Thomas, 

I checked with Thong this morning, the failure occurred due to the JPP document was modified on test machine, so a check out code process failed. That the reason of the failure.

Thong was solved it.

Thank you, 
Son

**Comment by test-fullautomation** [comment]
> Hello Thomas,
> 
> I checked with Thong this morning, the failure occurred due to the JPP document was modified on test machine, so a check out code process failed. That the reason of the failure.
> 
> Thong was solved it.
> 
> Thank you, Son

O.K. I merge...

**Pull request merged**
