### PR TITLE
Added further JSONP self test files (for tests of dynamic import)

### PR DESCRIPTION
**Pull request by HolQue**
Test case: `"[import]" : "./dynamic_imports/mixed_import.jsonp"`

A JSONP file (`mixed_import`) imports with a dynamic path another file (`AA`)
that imports with a fix path another file (`BB`)
that imports with a dynamic path another file (`CC`)
that imports with a fix path another file (`DD`)

The computation stops at level '`BB`' and the import of level '`CC`' is not resolved:

 ```
'[import]': '... /dynamic_imports/AA/BB/CC/imported.CC.M.jsonp',
 'level': 'BB'
```

Seems that the problem is caused by a switch from a dynamic path to a fix path.

Expected is level '`DD.3`'

### CODE REVIEW

**Review by test-fullautomation — COMMENTED** [review]
Hi Holger,
looks good to me!
Thank you,
 Thomas

**Comment by HolQue** [comment]
Hmm, this statement from above is wrong: "_Seems that the problem is caused by a switch from a dynamic path to a fix path._"

It's other way round: The switch from fix to dynamic does not work.

**Comment by HolQue** [comment]
JPP_1106
JPP_1107
JPP_1108

**Comment by HolQue** [comment]
JPP_1106
JPP_1107
JPP_1108
run successful now

**Pull request merged**
