### PR TITLE
Added dotdict format feature for JSON file.

### PR DESCRIPTION
**Pull request by namsonx**

### CODE REVIEW

**Review by HolQue — COMMENTED** [review]
Hi Son,

I have some general hints only:

Does this change have any impact on the Testsuites Management (= are corresponding changes required there, maybe schema adaptions) - or is this change relevant for the Json Preprocessor only?

@ThPoll
A JSON file example would be helpful, but this is a task for:
https://github.com/test-fullautomation/python-jsonpreprocessor/pull/35

@namsonx 
Is a self test for the new feature available?

@HolQue 
It will be a task for me to add an dotdict format example also in the documentation and the tutorial of the Testsuites Management.

**Comment by namsonx** [comment]
Hello Holger,

This change does not require any update in the Testsuites Management, it is only relevant to JsonPreprocessor.
I will create the selftest for this new feature in another commit soon.

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

I tested the feature in the context of the Testsuites Management. Some combinations do not work:

https://github.com/test-fullautomation/robotframework-testsuitesmanagement/issues/145

**Comment by namsonx** [comment]
Hello Holger,

"""
Outcome:
The value of ddKeyB_param is ddKeyB_value (like expected)

I extend the above code with:

${params}['global']['dTestDict']['ddKeyA'] : {"ddKeyA_2" : "ddKeyA_2_value"},

Some more complicated tests fail:

Code:
"ddKeyA_2_param_1" : ${params.global.dTestDict.ddKeyA.ddKeyA_2}

Outcome:
[ ERROR ] Loading of JSON configuration file failed! Reason: The variable 'params['global']['dTestDict']['ddKeyA']['ddKeyA_2']' is not available!
"""
This issue was fixed in the latest commit, could you please help me check again.

For the case ""ddKeyA_2_param_2" : ${params.global.dTestDict.ddKeyA}['ddKeyA_2']", I was not aware of the way we mix dotdict format with traditional format in the same nested param. We will discuss more about this scenario in next sync up meeting.

Thank you,
Son

**Comment by test-fullautomation** [comment]
Hi Son,
very good!
I merge this state as intermediate version?
I feared that the regexps get larger now, but filtering for and processing "." separately might be a good solution.

One question:
Which error message do I get if an object is not existing? e.b. `variable1.not_ex_object`

Thank you,
 Thomas

**Review by test-fullautomation — APPROVED** [review]
please refer to my comment.

**Pull request merged**
