### PR TITLE
Minior update variable name

### PR DESCRIPTION
**Pull request by namsonx**

### CODE REVIEW

**Review by HolQue — CHANGES_REQUESTED** [review]
Hi Son,

the variable is renamed only once in constructor. At all further positions still the old name is present.

I wonder how this can work. Because: When you work with a variable, but you do not initialize this variable in constructor any more (like previously), and this has no consequences, no errors, then you have a severe issues in your software architecture. Please check your code.


Addendum: I overlooked the error message!

JsonPreprocessor throws exception now:

`''CJsonPreprocessor' object has no attribute 'lUpdatedParams''!`

**Comment by HolQue** [comment]
Hi Son,

impact of this issue much higher than expected:

https://github.com/test-fullautomation/python-jsonpreprocessor/issues/98#issuecomment-1655637972

**Comment by namsonx** [comment]
Hello Holger, 

Opps, sorry my mistake. I forgot update other locations.
I will update!

Thank you,
Son

**Review by test-fullautomation — APPROVED** [review]
Hi Son,
looks good to me!
Thank you,
 Thomas

**Pull request merged**
