### PR TITLE
Adds selftest for utf-8 encoding.

### PR DESCRIPTION
**Pull request by namsonx**

### CODE REVIEW

**Comment by test-fullautomation** [comment]
Hi Son,
very good!
Please add five tests:
1. import into utf-8 file "normal" data
2. import into utf-8 file another utf-8 file
3. import into  "normal" file utf-8 file
4. create parameter where key and value have utf-8 data. Overwrite other existing value with ${utf-8 key}
5. like 4, but nested

Thank you,
 Thomas

**Review by test-fullautomation — APPROVED** [review]
Hi Son,
looks good to me, please read above finding.
Thank you,
 Thomas

**Review by test-fullautomation — CHANGES_REQUESTED** [review]
Hi Son,
please check my findings.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi Son,
please provide the requested additional tests.
Thank you, 
Thomas

**Comment by namsonx** [comment]
Hello Thomas,

I have just added more unittest cases for utf-8 handling.

Thank you

**Review by test-fullautomation — APPROVED** [review]
Hi Son,

looks good to me!

Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi Son,
there is a merge conflict in atest/jsonpreprocessor/jsonpreprocessor_unittest.py 
Please solve this.
Thank you,
 Thomas

**Review by test-fullautomation — CHANGES_REQUESTED** [review]
Hi Son,
unfortunately I can still not merge due to merge conflicts.
Please solve this as soon as possible.
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas,

I have just resolved conflict of this pull-request.

Thank you,
Son

**Review by test-fullautomation — APPROVED** [review]
Hi Son,
uups. sorry, I have still conflicts here with `test_jsonpreprocessor.py`.
Thank you,
 Thomas

**Review by test-fullautomation — CHANGES_REQUESTED** [review]
Hi Son,
I have unfortunately still merge confilcts.
Please solve this.
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas,

I have just resolved the merge conflict, you can merge it now :)

Thank you,
Son

**Review by test-fullautomation — APPROVED** [review]

**Pull request merged**
