### PR TITLE
Interface description maintenance

### PR DESCRIPTION
**Pull request by HolQue**
Please keep in mind: Most of the methods are private. And private methods are not part of the pdf documentation per default. Nevertheless: I updated them all.

There are some methods left that are public and without interface description. By occasion this gap should be filled. But this is not on me, because I do not know the code so much well.

### CODE REVIEW

**Review by test-fullautomation — APPROVED** [review]
Hi Holger,
looks good to me!
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi @HolQue ,
can you please solve the merge conflicts with Son's stabi branch. I would merge immediately.
Thank you,
 Thomas

**Comment by HolQue** [comment]
Replaced by

https://github.com/test-fullautomation/python-jsonpreprocessor/pull/228

This PR can be deleted.

**Comment by test-fullautomation** [comment]
closed as per request.

**Pull request closed without merging**
