### PR TITLE
Namsonx/task/stabi branch

### PR DESCRIPTION
**Pull request by namsonx**

### CODE REVIEW

**Review by HolQue — CHANGES_REQUESTED** [review]
Hi Son,

please consider my comments in corresponding ticket:

https://github.com/test-fullautomation/python-jsonpreprocessor/issues/153#issuecomment-1880913567
https://github.com/test-fullautomation/python-jsonpreprocessor/issues/153#issuecomment-1881088016
https://github.com/test-fullautomation/python-jsonpreprocessor/issues/153#issuecomment-1881125319
https://github.com/test-fullautomation/python-jsonpreprocessor/issues/153#issuecomment-1881146345

**Comment by test-fullautomation** [comment]
> Hi Son,
> 
> please consider my comments in corresponding ticket:
> 
> [#153 (comment)](https://github.com/test-fullautomation/python-jsonpreprocessor/issues/153#issuecomment-1880913567) [#153 (comment)](https://github.com/test-fullautomation/python-jsonpreprocessor/issues/153#issuecomment-1881088016) [#153 (comment)](https://github.com/test-fullautomation/python-jsonpreprocessor/issues/153#issuecomment-1881125319) [#153 (comment)](https://github.com/test-fullautomation/python-jsonpreprocessor/issues/153#issuecomment-1881146345)

Hi Son,

please consider the four above linked issues as prio1 bugs.
Please provide as soon as possible a pull-request for this.

Thank you,
 Thomas

**Comment by namsonx** [comment]
> > Hi Son,
> > please consider my comments in corresponding ticket:
> > [#153 (comment)](https://github.com/test-fullautomation/python-jsonpreprocessor/issues/153#issuecomment-1880913567) [#153 (comment)](https://github.com/test-fullautomation/python-jsonpreprocessor/issues/153#issuecomment-1881088016) [#153 (comment)](https://github.com/test-fullautomation/python-jsonpreprocessor/issues/153#issuecomment-1881125319) [#153 (comment)](https://github.com/test-fullautomation/python-jsonpreprocessor/issues/153#issuecomment-1881146345)
> 
> Hi Son,
> 
> please consider the four above linked issues as prio1 bugs. Please provide as soon as possible a pull-request for this.
> 
> Thank you, Thomas

Hello Thomas, Hello Holger,

Thank you for your findings!
I resolved all 4 issues based on your comment in [the latest commit 34a35aa697fc2](https://github.com/test-fullautomation/python-jsonpreprocessor/pull/181/commits/34a35aa697fc2c8c05ce9584f2aa3cdfdf76b6d1) in this pull-request.

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

restest mostly successful.

But one curious observation left: JPP_1057 executed separately, causes:

`'Could not set variable 'testdict[C][C]' with value '4'! Reason: name 'C' is not defined'`

That is OK.

But executed together with other test cases, the error message changes to:

`'Could not set variable 'testdict[C][C]' with value '4'! Reason: 2'`

Seems that there are still interdependencies.

**Comment by namsonx** [comment]
> Hi Son,
> 
> restest mostly successful.
> 
> But one curious observation left: JPP_1057 executed separately, causes:
> 
> `'Could not set variable 'testdict[C][C]' with value '4'! Reason: name 'C' is not defined'`
> 
> That is OK.
> 
> But executed together with other test cases, the error message changes to:
> 
> `'Could not set variable 'testdict[C][C]' with value '4'! Reason: 2'`
> 
> Seems that there are still interdependencies.

Hello Holger,

I will check the test case ID JPP_1057 and analyze the root cause.

Thank you,
Son

**Comment by namsonx** [comment]
> Hi Son,
> 
> restest mostly successful.
> 
> But one curious observation left: JPP_1057 executed separately, causes:
> 
> `'Could not set variable 'testdict[C][C]' with value '4'! Reason: name 'C' is not defined'`
> 
> That is OK.
> 
> But executed together with other test cases, the error message changes to:
> 
> `'Could not set variable 'testdict[C][C]' with value '4'! Reason: 2'`
> 
> Seems that there are still interdependencies.

Hello Holger,

I have just pushed [new commit a95c86f271780](https://github.com/test-fullautomation/python-jsonpreprocessor/pull/181/commits/a95c86f271780a3d06cdd5d583e51ad3afa9de18) to fix the issue you mentioned in test case ID JPP_1057

Thank you,
Son

**Review by test-fullautomation — APPROVED** [review]
Hi Son,
looks good to me!
Thank you,
 Thomas

**Pull request merged**
