### PR TITLE
Improve nested parameter substitution

### PR DESCRIPTION
**Pull request by namsonx**

### CODE REVIEW

**Comment by HolQue** [comment]
Hi Son,

there is a merge conflict with

origin/namsonx/fixbug/98/memory_interferences

Please resolve.

**Comment by namsonx** [comment]
Hi Holger,

I merged the conflict in branch [namsonx/testing/testing_branch](https://github.com/test-fullautomation/python-jsonpreprocessor/tree/namsonx/testing/testing_branch)

Thank you,
Son

**Review by test-fullautomation — CHANGES_REQUESTED** [review]
Hi Son,
please solve the merge conflict.
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas,

Conflict was resolved.

Thank you,
Son

**Review by HolQue — COMMENTED** [review]
Hi Son,

I do not understand what is going on here. Comparing the test log file of this branch with the test log file of your test branch some days ago, I observe that two more test cases fail. Reason is that a previously fixed issue is back:

```
Found deviating return values
(1) '[DICT] (51/7) > {param_07} [STR]  :  'true''   > (expected)
(2) '[DICT] (51/7) > {param_07} [STR]  :  '"true"''   > (returned)
```
What exactly shall be improved in this pull request? It would be helpful to refer to a concrete issue when you provide fixes.

**Comment by namsonx** [comment]
Hello Holger,

The issue you mentioned above is fixed in other pull-request #110 which is not yet merged.
All latest commits were merged to my testing branch - namsonx/testing/testing_branch. Could you please verify issue using this testing branch?

Thank you,
Son

**Pull request closed without merging**
