### PR TITLE
Fix issue 83, jsonp configuration file path computation.

### PR DESCRIPTION
**Pull request by namsonx**

### CODE REVIEW

**Review by HolQue — CHANGES_REQUESTED** [review]
Hi Son,

relative paths work now!!

But please replace:

```
jFile=jFile.strip()

if not re.match("^[a-zA-Z]:",jFile) and not re.match("^[\\/]",jFile):
    jFile = CString.NormalizePath(jFile)

if  not(os.path.isfile(jFile)):
    raise Exception(f"File '{jFile}' is not existing!")

self.lImportedFiles.append(jFile)
self.jsonPath = os.path.dirname(jFile)

try:
    sJsonData= self.__load_and_removeComments(os.path.abspath(jFile))
```

with something like:

```
# at first normalize:
jFile = CString.NormalizePath(jFile) # (NormalizePath does also the jFile.strip() for you ;-)

# at second check existence
if  not(os.path.isfile(jFile)):
    raise Exception(f"File '{jFile}' is not existing!")

# only if file exist, further checks makes sense:
if not re.match("^[a-zA-Z]:",jFile) and not re.match("^[\\/]",jFile):
   # further consequences if required

self.lImportedFiles.append(jFile)
self.jsonPath = os.path.dirname(jFile)

try:
    sJsonData= self.__load_and_removeComments(jFile) # jFile is already normalized, therefore os.path.abspath is not necessary
```

**Review by test-fullautomation — CHANGES_REQUESTED** [review]
Hi Son,
very good.
Please consider Holgers finding and provide as soon as possible a new pull-request.,
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Holger, 

Thank you for your comments!

Hello Thomas, I have just updated the pull-request.

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

what is this:

`jFile = CString.NormalizePath(jFile.strip())`

?

I already mentioned several times now: NormalizePath does a strip() also. Therefore no need to do this when calling NormalizePath().

Please consider my previous comment:

```
# at first normalize:
jFile = CString.NormalizePath(jFile) # (NormalizePath does also the jFile.strip() for you ;-)

```

**Comment by namsonx** [comment]
Hello Holger,

Sorry for the mistake! I've done it as a habit.
I remove .strip()

Thank you,
Son

**Comment by test-fullautomation** [comment]
Hi @namsonx ,
what is the status of this ticket?
Thank you,
 Thomas

**Review by test-fullautomation — APPROVED** [review]
Hi Son,
merged after discussion with Holger,
Thank you,
 Thomas

**Pull request merged**
